api = "0.7"

[buildpack]
  id = "misorobotics/google-cloud-sdk"
  version = "0.1.0"
  name = "Google Cloud SDK Buildpack"
  homepage = "https://github.com/MisoRobotics/buildpack-google-cloud-sdk"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/MisoRobotics/buildpack-google-cloud-sdk/blob/main/LICENSE"

[metadata]
  include-files = ["bin/build", "bin/detect", "buildpack.toml"]

[[stacks]]
  id = "google"
